url: "ironikerine.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "EEVC Lab" # the name of your site, e.g. ACME Corp.
description: "Earthquake Engineering & Vibration Control Lab"
#theme: academic-jekyll-theme

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-50EJ47P74N"
    anonymize_ip         : # true, false (default)